base/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.HomepageView.as_view(), name='homepage'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='base:homepage'), name='logout'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('<slug:slug>', views.PostDetailView.as_view(), name='post_detail'),
    path('create/', views.PostCreateWithInlinesView.as_view(), name='create'),
    path('update/<slug:slug>', views.PostUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>', views.PostDeleteView.as_view(), name='delete'),
]

iosifsolomon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('base.urls', namespace="base")),
    path('blog/', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Iosif Solomon'
admin.site.site_title = 'Iosif Solomon'

base/models.py
from django.db import models
from django.utils import timezone

from .managers import PublishedManager


class BasePublishModel(models.Model):
    class PublishStatus(models.TextChoices):
        DRAFT = 'DR', 'Draft'
        PUBLISHED = 'PU', 'Published'
        PRIVATE = 'PR', 'Private'

    status = models.CharField(max_length=2, default=PublishStatus.DRAFT, choices=PublishStatus.choices)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    published_on = models.DateTimeField(
        auto_now_add=False, auto_now=False, null=True)

    def save(self, *args, **kwargs):
        if self.is_published and self.published_on is None:
            self.published_on = timezone.now()
        else:
            self.published_on = None
        super().save(*args, **kwargs)

    @property
    def is_published(self):
        return self.status == self.PublishStatus.PUBLISHED

    @property
    def is_draft(self):
        return self.status == self.PublishStatus.DRAFT

    @property
    def is_private(self):
        return self.status == self.PublishStatus.PRIVATE

    objects = PublishedManager()

    class Meta:
        abstract = True

blog/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from taggit.managers import TaggableManager
from cloudinary.models import CloudinaryField

from base.models import BasePublishModel
from base.utils import slugify_pre_save


class Post(BasePublishModel):
    title = models.CharField(max_length=255)
    text = models.TextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True, db_index=True)
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-updated_on', '-created_on']
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'


pre_save.connect(slugify_pre_save, sender=Post)


class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="post_images")
    image = CloudinaryField("image", resource_type="image", transformation={"quality": "auto:eco"})

    def __str__(self):
        return self.post.title

projects/models.py
from django.db import models


class Tool(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='images/')
    src_url = models.URLField(blank=True)
    live_url = models.URLField(blank=True)
    tools = models.ForeignKey(Tool, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import Post, PostImage
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('published_on', 'slug',)
        widgets = {
            'title': forms.TextInput(),
            'text': SummernoteWidget(),
        }


class PostImageForm(forms.ModelForm):
    class Meta:
        model = PostImage
        fields = ['image', ]
        widgets = {
            'image': forms.FileInput()
        }

base/views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import TemplateView


class HomepageView(TemplateView):
    template_name = 'base/index.html'

    def get_context_data(self, **kwargs):
        context = super(HomepageView, self).get_context_data(**kwargs)
        return context


class UserLoginView(LoginView):
    template_name = 'registration/login.html'
    fields = '__all__'
    # redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('base:homepage')

blog/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from hitcount.views import HitCountDetailView
from extra_views import InlineFormSetFactory, CreateWithInlinesView, UpdateWithInlinesView, SuccessMessageMixin

from blog.forms import PostForm, PostImageForm
from blog.models import Post, PostImage


class PostListView(ListView):
    template_name = 'blog/post_list.html'
    model = Post
    context_object_name = 'posts'

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.is_staff:
            return qs
        return qs.filter(status='PU')


class PostDetailView(HitCountDetailView):
    template_name = 'blog/post_detail.html'
    model = Post
    context_object_name = 'post'
    count_hit = True

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        slug = self.kwargs.get(self.slug_url_kwarg)
        post = get_object_or_404(Post, slug=slug)
        if self.request.user.is_staff:
            return post
        if post.status == 'PR':
            messages.error(self.request, "This post is private")
            return Post.objects.none()
        elif post.status == 'DR':
            messages.warning(self.request, "This post is not yet published")
            return Post.objects.none()
        else:
            return post


class PostImageInlineFormset(InlineFormSetFactory):
    model = PostImage
    form_class = PostImageForm
    fields = '__all__'
    extra_forms = 1
    can_delete = True

    def get_factory_kwargs(self):
        factory_kwargs = super().get_factory_kwargs()
        factory_kwargs.update({'extra': self.extra_forms})
        return factory_kwargs


class PostCreateWithInlinesView(LoginRequiredMixin, CreateWithInlinesView):
    model = Post
    form_class = PostForm
    inlines = [PostImageInlineFormset, ]
    template_name = 'blog/post_create.html'
    success_url = None

    # def forms_valid(self, form, inlines):
    #     # form.instance.publi = self.request.user
    #     self.object = form.save()
    #     response = self.form_valid(form)
    #     for formset in inlines:
    #         for form in formset:
    #             new_photo = form.save(commit=False)
    #             new_photo.post = self.object
    #             new_photo.save()
    #     messages.success(self.request, f"<b>{self.object.title}</b> created successfully")
    #     return response

    def get_success_url(self):
        return reverse_lazy('blog:post_detail', kwargs={'slug': self.object.slug})


# class PostCreateView(LoginRequiredMixin, CreateView):
#     model = Post
#     template_name = 'blog/post_create.html'
#     form_class = PostForm


class PostUpdateView(UpdateView):
    model = Post
    template_name = 'blog/post_update.html'


class PostDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:home')
    permission_required = 'post.delete_post'

projects/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
{% load django_simple_bulma %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon -->
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <!-- Bulma CSS CDN -->
    {% bulma %}

    <!-- Font Awesome -->
    {% font_awesome %}

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <title>{% block title %} {% endblock title %}</title>

</head>
<body>
<div class="block has-background-light">
    {% include 'includes/navbar.html' %}
    {% block content %}

    {% endblock content %}

    {% block footer %}
        {% include 'includes/footer.html' %}
    {% endblock footer %}
</div>
<script src="{% static 'js/main.js' %}"></script>
{% block javascript %}{% endblock javascript %}
</body>
</html>

templates/base/contact.html
{% extends 'base.html' %}

{% block title %}
    Contact Me
{% endblock %}

{% block content %}

{% endblock %}

templates/base/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Iosif Solomon{% endblock %}

{% block content %}

    <!-- Hero Section -->
    <section id="hero-section" class="hero is-light is-fullheight-with-navbar">
        <div class="hero-body">
            <div class="container">
                <p class="title has-text-primary is-2 has-text-weight-normal is-family-code">
                    <span style="color: rgb(171, 178, 191)">full_name</span><span
                        style="color: rgb(198, 120, 221)"> = </span><span style="color:rgb(152, 195, 121)">"Iosif Solomon"</span>
                </p>
                <p class="title is-2 has-text-weight-normal is-family-monospace">
                    <span style="color: rgb(171, 178, 191)">role</span><span style="color: rgb(198, 120, 221)"> = </span><span
                        style="color:rgb(152, 195, 121)">"Python
                    Developer"</span>
                </p>
                <p class="title is-2 has-text-weight-normal is-family-monospace">
                    <span style="color: rgb(171, 178, 191)">is_available</span><span style="color: rgb(198, 120, 221)"> = </span><span
                        style="color:rgb(209, 154, 102)">True</span>
                </p>

            </div>
        </div>
    </section>

    <!-- Projects Section -->
    <section class="section">
        <div class="container">
            <h1 class="title has-text-centered is-1 has-text-dark pb-5" id="my-projects">Projects</h1>
{#            <h2 class="subtitle has-text-centered">These are some examples of my work as a backend developer</h2>#}

            <div class="columns is-centered is-multiline">
                <div class="column is-4-desktop is-6-tablet">
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title has-text-grey-dark is-size-5">
                                Django Photography
                            </p>
                        </header>
                        <div class="card-image">
                            <figure class="image is-4by3">
                                <img src="{% static 'images/django_photography.png' %}" alt="Placeholder image">
                            </figure>
                        </div>

                        <div class="card-content">

                            <div class="content">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                Phasellus nec iaculis mauris. <a>@bulmaio</a>.
                                <a href="#">#css</a> <a href="#">#responsive</a>
                                <br>
                                <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
                            </div>
                        </div>
                        <footer class="card-footer">
                            <p class="card-footer-item">
                              <span>
                                Check live <a href="https://django-photography.herokuapp.com/">project</a>
                              </span>
                            </p>
                            <p class="card-footer-item">
                              <span>
                                View code on <a href="#">Github</a>
                              </span>
                            </p>
                        </footer>
                    </div>
                </div>
                <div class="column is-4-desktop is-6-tablet">
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">
                                UPU-SMURD Cluj
                            </p>
                            <button class="card-header-icon" aria-label="more options">
                              <span class="icon">
                                <i class="fas fa-angle-down" aria-hidden="true"></i>
                              </span>
                            </button>
                        </header>
                        <div class="card-image">
                            <figure class="image is-4by3">
                                <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
                            </figure>
                        </div>

                        <div class="card-content">

                            <div class="content">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                Phasellus nec iaculis mauris. <a>@bulmaio</a>.
                                <a href="#">#css</a> <a href="#">#responsive</a>
                                <br>
                                <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
                            </div>
                        </div>
                        <footer class="card-footer">
                            <p class="card-footer-item">
                              <span>
                                Check live <a href="https://django-photography.herokuapp.com/">project</a>
                              </span>
                            </p>
                            <p class="card-footer-item">
                              <span>
                                View code on <a href="#">Github</a>
                              </span>
                            </p>
                        </footer>
                    </div>
                </div>
                <div class="column is-4-desktop is-6-tablet">
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">
                                Infografic Covid-19
                            </p>
                            <button class="card-header-icon" aria-label="more options">
                              <span class="icon">
                                <i class="fas fa-angle-down" aria-hidden="true"></i>
                              </span>
                            </button>
                        </header>
                        <div class="card-image">
                            <figure class="image is-4by3">
                                <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
                            </figure>
                        </div>

                        <div class="card-content">

                            <div class="content">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                Phasellus nec iaculis mauris. <a>@bulmaio</a>.
                                <a href="#">#css</a> <a href="#">#responsive</a>
                                <br>
                                <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
                            </div>
                        </div>
                        <footer class="card-footer">
                            <p class="card-footer-item">
                              <span>
                                Check live <a href="https://django-photography.herokuapp.com/">project</a>
                              </span>
                            </p>
                            <p class="card-footer-item">
                              <span>
                                View code on <a href="#">Github</a>
                              </span>
                            </p>
                        </footer>
                    </div>
                </div>
                <div class="column is-4-desktop is-6-tablet">
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">
                                Lost Documents
                            </p>
                            <button class="card-header-icon" aria-label="more options">
                              <span class="icon">
                                <i class="fas fa-angle-down" aria-hidden="true"></i>
                              </span>
                            </button>
                        </header>
                        <div class="card-image">
                            <figure class="image is-4by3">
                                <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
                            </figure>
                        </div>

                        <div class="card-content">

                            <div class="content">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                Phasellus nec iaculis mauris. <a>@bulmaio</a>.
                                <a href="#">#css</a> <a href="#">#responsive</a>
                                <br>
                                <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
                            </div>
                        </div>
                        <footer class="card-footer">
                            <p class="card-footer-item">
                              <span>
                                Check live <a href="https://django-photography.herokuapp.com/">project</a>
                              </span>
                            </p>
                            <p class="card-footer-item">
                              <span>
                                View code on <a href="#">Github</a>
                              </span>
                            </p>
                        </footer>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/blog/post_create.html
{% extends 'base.html' %}
{% load bulma_tags %}

{% block title %}
    Create new post
{% endblock %}

{% block content %}
    <section class="section">
        <div class="container box px-5">
            <div class="notification">
                <h1 class="title py-5 has-text-centered">Create a new blog post</h1>
            </div>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="columns is-multiline">
                    <div class="column is-two-thirds">
                        {{ form.title|bulma }}
                    </div>
                    <div class="column is-one-fifth">
                        {{ form.tags|bulma }}
                    </div>
                    <div class="column">
                        {{ form.status|bulma }}
                    </div>
                </div>
                <div class="columns">
                    <div class="column is-full">
                        {{ form.text|bulma }}
                    </div>
                </div>
                <div>
                    {% for formset in inlines %}
                        {{ formset.management_form }}

                        <div class="columns is-multiline is-variable" id="inline-form">
                            {% for image_form in formset %}
                                <div class="column  is-5-desktop image-form box has-background-primary-light mx-4">
                                    <button class="delete delete-image-form is-pulled-right"></button>
                                    <div class="file is-small is-primary has-name">
                                        {{ image_form|bulma }}
                                    </div>
                                </div>
                                <div id="form-end-hidden" style="display: none;"></div>
                            {% endfor %}

                        </div>
                        <div class="block">
                            <button class="button is-primary  is-inverted  is-rounded" id="add-image-form"><i
                                    class="fas fa-plus"></i></button>
                        </div>

                    {% endfor %}
                </div>


                <div class="field pb-6">
                    <button type="submit" class="button is-success is-pulled-right">Create post</button>
                </div>
            </form>
        </div>
    </section>

    {#    <div class="container box">#}
    {#        <form action="" method="post" enctype="multipart/form-data">#}
    {#            {% csrf_token %}#}
    {#            {{ form|bulma }}#}
    {##}
    {#            {% for formset in inlines %}#}
    {#                {{ formset|bulma }}#}
    {#            {% endfor %}#}
    {#            <input type="submit" value="Submit"/>#}
    {#        </form>#}
    {#    </div>#}
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}

{% load hitcount_tags %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    {% include 'includes/messages.html' %}
    {% if post %}
        <div class="container box">
            <h1 class="title">{{ post.title }}</h1>
            <p>{{ post.created_on|date:"d M Y" }}</p>
            {% get_hit_count for post as hit_count %}
            <p>{{ hit_count }} view{{ hit_count|pluralize }}</p>
            {% for tag in post.tags.all %}
                <span>#{{ tag }} </span>
            {% endfor %}

            {% if post.text %}
                {% autoescape off %}
                    <div class="content">{{ post.text|linebreaks }}</div>
                {% endautoescape on %}
            {% endif %}

            {% if post.post_images %}
                {% for photo in post.post_images.all %}
                    <img src="{{ photo.image.url }}" alt="" style="width: 100%; padding: 7px;">
                {% endfor %}
            {% endif %}


        </div>

    {% endif %}
{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}

{% load hitcount_tags %}

{% block title %}
    Blog - Iosif Solomon
{% endblock %}

{% block content %}
    {% include 'includes/messages.html' %}

    <div class="container">
        <section class="hero has-background-success-light radius has-text-success-dark">
            <div class="hero-body has-text-centered">
                <p class="title has-text-primary is-spaced is-size-1 has-text-weight-bold">My Blog</p>
                <p class="subtitle">A collection of programming technologies related articles</p>
            </div>
        </section>
    </div>



    <section class="section">
        <div class="container">
            {% for post in posts %}
                <div class="box">
                    <div class="content is-medium">
                        <h1><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
                        <p>{{ post.published_on|date:"d M Y" }}</p>
                        {% get_hit_count for post as hit_count %}
                        <p>{{ hit_count }} view{{ hit_count|pluralize }}</p>
                        {% for tag in post.tags.all %}
                            <span class="tag">#{{ tag }}</span>
                        {% endfor %}

                        {% if post.text %}
                            {% autoescape off %}
                                <div class="content">{{ post.text }}</div>
                            {% endautoescape on %}
                        {% endif %}

                        {% if post.post_images %}
                            {% for photo in post.post_images.all %}
                                <img class="image" src="{{ photo.image.url }}" alt="">
                            {% endfor %}
                        {% endif %}

                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

templates/includes/footer.html
<footer class="footer" style="margin-top: auto;">
    <div class="content has-text-centered">
        <p>
            Created with <a href="">Django</a> and <a href="">Bulma</a>. by Iosif Solomon
            <a href="{% url 'base:login' %}"><i class="fas fa-sign-in-alt"></i></a>
        </p>
    </div>
</footer>

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        {% ifchanged %}
            <div class="container">
                <div class="notification is-{{ message.tags }}">
                    <button class="delete"></button>
                    {{ message|safe }}
                </div>
            </div>
        {% endifchanged %}
    {% endfor %}
{% endif %}

templates/includes/navbar.html
<section class="hero">
    <nav class="navbar is-fixed is-spaced is-transparent" role="navigation" aria-label="main navigation" id="mainNavbar">
        <div class="navbar-brand">
            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarMenu">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarMenu" class="navbar-menu">
            <div class="navbar-end is-size-5" id="main-navbar-end">
                <a class="navbar-item" href="{% url 'base:homepage' %}">Home</a>
                <a class="navbar-item" href="{% url 'blog:home' %}">Blog</a>
                <a class="navbar-item" href="#my-projects">Projects</a>
                <a class="navbar-item" href="">Resume</a>
                <a class="navbar-item">Contact</a>

                {% if request.user.is_authenticated and request.user.is_staff %}
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link is-arrowless">
                            <i class="fa fa-user-circle fa-lg"></i>&nbsp;&nbsp;
                            <p class="is-size-6 has-text-weight-bold">
                                {{ user.username|title }}
                            </p>
                        </a>
                        <div class="navbar-dropdown">
                            <a href="{% url 'base:homepage' %}admin/" class="navbar-item">
                                <i class="fas fa-tools"></i>&nbsp;
                                Site Admin
                            </a>
                            <a href="{% url 'blog:create' %}" class="navbar-item">
                                <i class="far fa-file-alt"></i>&nbsp;
                                Create blog post
                            </a>
                            <a class="navbar-item">
                                <i class="fas fa-project-diagram"></i>&nbsp;
                                Add new project
                            </a>
                            <a class="navbar-item">
                                <i class="far fa-chart-bar"></i>&nbsp;
                                See website stats
                            </a>
                            <hr class="navbar-divider">
                            <a href="{% url 'base:logout' %}" class="navbar-item">
                                <i class="fas fa-sign-out-alt"></i>&nbsp;
                                Log Out
                            </a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </nav>
</section>